# Generated by Django 4.0.3 on 2022-03-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('genere', models.CharField(choices=[('Contemporary', 'Contemporary'), ('Detective', 'Detective'), ('Dystopian', 'Dystopian'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], default='Contemporary', max_length=50)),
                ('released', models.DateField()),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
